web/urls.py
from django.conf.urls import url

from . import views

app_name = 'web'

urlpatterns = [
    # ex: /
    url(r'^$', views.index, name='index'),
    # ex: /cam/
    url(r'^cam$', views.cam, name='cam'),
    # ex: /linked/
    url(r'^linked$', views.linked, name='linked'),
    # ex: /new_token/
    url(r'^new_token$', views.new_token, name='new_token'),
    # ex: /registry_token/
    url(r'^registry_token', views.registry_token, name='registry_token'),
    # ex: /is_registred/
    url(r'^is_registred', views.is_registred, name='is_registred'),
    # ex: /uploadFile/
    url(r'^uploadFile', views.uploadFile, name='uploadFile'),
    # ex: /downloadFile/
    url(r'^downloadFile', views.downloadFile, name='downloadFile'),

]

web/models.py
from django.db import models

class Sesion(models.Model):
    token = models.CharField(max_length=200, verbose_name='Token', null=False, primary_key=True)

    def __str__(self):
        return self.token

class Document(models.Model):
    docfile = models.FileField(upload_to='documents/')
    token = models.CharField(max_length=200, verbose_name='Token', null=False)
    def __str__(self):
        return self.docfile.name

web/forms.py
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(label='Select a file')

web/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from web.models import Sesion
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from web.models import Document
from web.forms import DocumentForm

import hashlib
import time

@csrf_exempt
def index(request):
    return render(request, 'web/index.html')

@csrf_exempt
def cam(request):
    return render(request, 'web/cam.html')

@csrf_exempt
def linked(request):
    return render(request, 'web/linked.html')

@csrf_exempt
def new_token(request):
    hash = hashlib.sha1()
    hash.update(str(time.time()).encode('utf-8'))
    return HttpResponse(hash.hexdigest())

@csrf_exempt
def registry_token(request):
    try:
        tk = request.COOKIES["cookie"]
        s = Sesion(token=tk)
        s.save()
    except:
        return HttpResponse("0")
    return HttpResponse("1")

@csrf_exempt
def is_registred(request):
    try:
        tk = request.COOKIES["cookie"]
        Sesion.objects.get(token=tk)
    except:
        return HttpResponse("0")

    tk = request.COOKIES["cookie"]
    Sesion.objects.get(token=tk).delete()
    return HttpResponse("1")


@csrf_exempt
def uploadFile(request):
    try:
        tk = request.COOKIES["cookie"]
        Document.objects.get(token=tk).delete()
    except:
        pass
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile = request.FILES['docfile'], token=request.COOKIES["cookie"])
            newdoc.save()

            # Redirect to the document list after POST
            return redirect('/')
        return HttpResponse("0")
    else:
        form = DocumentForm() # A empty, unbound form
        return HttpResponse("-1")



@csrf_exempt
def downloadFile(request):
    try:
        tk = request.COOKIES["cookie"]
        doc = Document.objects.get(token=tk)
        return HttpResponse(doc.docfile._get_url())
    except:
        return HttpResponse("-1")

web/templates/web/cam.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>QRLinker</title>
    <link rel="icon" href="{% static "web/fonts/icon.png" %}">
    <!-- Bootstrap Core CSS -->
    <link href="{% static "web/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "web/css/1-col-portfolio.css" %}" rel="stylesheet">
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'web:index' %}">QR Linker</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a onclick="changeExplain()">About</a>
                        <script>
                        function changeExplain() {
                            document.getElementById("explain").innerHTML = "This web side has been done in HackGT@UPC 2016 \n thanks to: \n     Circosta for https://github.com/cirocosta/qcode-decoder\n     startbootstrap for http://startbootstrap.com/template-overviews/1-col-portfolio/\n     Irsjng for https://larsjung.de/jquery-qrcode/";
                        }
                        </script>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <!-- QR -->
        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    
                    <!-- AQUI CODE DE CAM -->
                    <video autoplay></video>
                    <script src="{% static "web/js/decode/qcode-decoder.min.js" %}"></script>
                    <script type="text/javascript">
                    (function () {
                        'use strict';

                        var qr = new QCodeDecoder();

                        if (!(qr.isCanvasSupported() && qr.hasGetUserMedia())) {
                        alert('Your browser doesn\'t match the required specs.');
                        throw new Error('Canvas and getUserMedia are required');
                        }

                        var video = document.querySelector('video');
                        var reset = document.querySelector('#reset');
                        var stop = document.querySelector('#stop');

                        function resultHandler (err, result) {
                            if (err)
                                return console.log(err.message);
                            alert(result);
                            document.cookie = "cookie=" + result;
			    $.post('registry_token', {cookie: result});
                            location.replace("./linked");
                        }
                        qr.decodeFromCamera(video, resultHandler);

                    })();
                    </script>
                    <!-- FINAL CODE DE CAM -->
                </a>
            </div>
            <div class="col-md-5">
                <!-- EXPLAIN AND BUTTONS-->
                <p id="explain">You can link 2 browsers. The first one whit the QR and the second click in "Cam" and scan the file. Next upload the file from one browser and the second will download</p>
                <!-- FINAL EXPLAIN AND BUTTONS -->
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static "web/js/jquery.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "web/js/bootstrap.min.js" %}"></script>


</body>

</html>

web/templates/web/index.html
{% load staticfiles %}
{% csrf_token %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>QRLinker</title>
    <link rel="icon" href="{% static "web/fonts/icon.png" %}">
    <!-- Bootstrap Core CSS -->
    <link href="{% static "web/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "web/css/1-col-portfolio.css" %}" rel="stylesheet">
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="">QR Linker</a> 
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a onclick="changeExplain()">About</a>
                        <script>
                        function changeExplain() {
                            document.getElementById("explain").innerHTML = "This web side has been done in HackGT@UPC 2016 \n thanks to: \n     Circosta for https://github.com/cirocosta/qcode-decoder\n     startbootstrap for http://startbootstrap.com/template-overviews/1-col-portfolio/\n     Irsjng for https://larsjung.de/jquery-qrcode/";
                        }
                        </script>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        <!-- QR -->
        <div class="row">
            <div class="col-md-7">
                    <!-- AQUI EL QR -->
                    <div id="container"></div>
                    <!-- FINAL QR -->
                    
                </a>
            </div>
            <div class="col-md-5">
                <!-- EXPLAIN AND BUTTONS-->
                <p id="explain">You can link 2 browsers. The first one whit the QR and the second click in "Cam" and scan the file. Next upload the file from one browser and the second will download</p>
                <input type="button" onclick="location.href='{% url 'web:cam' %}';" value="Cam" />
                <!-- FINAL EXPLAIN AND BUTTONS -->
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static "web/js/jquery.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "web/js/bootstrap.min.js" %}"></script>
    
    <!-- QR LIBS  -->
    <script src="{% static "web/js/jquery.min.js" %}"></script>
    <script src="{% static "web/js/jquery-qrcode-0.14.0.js" %}"></script>
    <script src="{% static "web/js/scripts.js" %}"></script>
    <!-- DECODE -->
    
    <!-- END QR LIBS -->
    
</body>

</html>

web/templates/web/linked.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>QRLinker</title>
    <link rel="icon" href="{% static "web/fonts/icon.png" %}">
    <!-- Bootstrap Core CSS -->
    <link href="{% static "web/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "web/css/1-col-portfolio.css" %}" rel="stylesheet">


</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'web:index' %}">QR Linker</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a onclick="changeExplain()">About</a>
                        <script>
                        function changeExplain() {
                            document.getElementById("explain").innerHTML = "This web side has been done in HackGT@UPC 2016 \n thanks to: \n     Circosta for https://github.com/cirocosta/qcode-decoder\n     startbootstrap for http://startbootstrap.com/template-overviews/1-col-portfolio/\n     Irsjng for https://larsjung.de/jquery-qrcode/";
                        }
                        </script>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">
        <!-- QR -->
        <div class="row">
            <div class="col-md-7">
                <!-- EXPLAIN AND BUTTONS-->
                <p id="explain">You can link 2 browsers. The first one whit the QR and the second click in "Cam" and scan the file. Next upload the file from one browser and the second will download</p>
                <!-- UPLOAD FILE -->
                <form action="uploadFile" enctype="multipart/form-data" method="post">
                    <p> Please specify a file, or a set of files:<br>
                        <input type="file" name="docfile" size="40">
                    </p>
                    <div>
                        <input type="submit" value="Send">
                    </div>
                </form>
                <!-- DOWNLOAD FILE -->
                <script>
                    setTimeout(function() {
                        var down = false;
                        setInterval(function() {
                        var posting = $.post('downloadFile');
                        posting.done(function(data) {
                            if (data !== "-1" && !down && !up) {
                            window.open(data);
                            down = true;
                            }
                        });
                        }, 1*1000);
                    }, 1*1000);
                </script>
                <!-- FINAL EXPLAIN AND BUTTONS -->
                </a>
            </div>
            <div class="col-md-5">
                <!-- AQUI EL FILE MANAGER -->
                <!-- FINAL FILE MANAGER -->
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static "web/js/jquery.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "web/js/bootstrap.min.js" %}"></script>
    
</body>

</html>